app: anchor-backend
services:
  - name: api
    type: web
    build:
      builder: buildpack
      buildCommand: cd backend && npm install && npm run build
    run:
      command: cd backend && npm run start:node
    ports:
      - port: 3000
        protocol: http
    env:
      - name: PORT
        value: "3000"
    healthcheck:
      http:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      timeoutSeconds: 10
